### ISSUE TITLE
undefined: xlib.Max

### ISSUE THREAD

**Issue by Rid-lin** [softlandia/cpd#1]
Приветствую.
Попробовал использовать библиотеку для конвертирования CP866 в UTF-8 и получил ошибку 
# github.com/softlandia/cpd
\github.com\softlandia\cpd@v0.0.0-20200117174517-8637e2108629\utf16be.go:20:18: undefined: xlib.Max
\github.com\softlandia\cpd@v0.0.0-20200117174517-8637e2108629\utf16le.go:21:18: undefined: xlib.Max

Я что-то делаю не так?

**Comment by softlandia** [comment]
Ошибочка вышла, забыл прописать в зависимостях 
Обнови cpd и закачай "github.com/softlandia/xlib"
Там у меня пара полезных функций, я их использую постоянно вот и забыл указать
Добавил в тесты конвертирование из CP866 в UTF, работает

**Comment by softlandia** [comment]
Я подумаю, может избавлюсь от дополнительных зависимостей.
Если что, конвертацию из CP866 в UTF-8 можно сделать одной строкой
s, _, err = transform.String(charmap.CodePage866.NewDecoder(), s)

**Comment by Rid-lin** [comment]
Странно, но не получается обновиться.
go get -u github.com/softlandia/cpd
go: finding github.com/softlandia/cpd latest
go: downloading github.com/softlandia/cpd v0.0.0-20200127145959-492f173dc3a2
go: extracting github.com/softlandia/cpd v0.0.0-20200127145959-492f173dc3a2
go: finding github.com/softlandia/xlib latest
# github.com/softlandia/cpd
go\pkg\mod\github.com\softlandia\cpd@v0.0.0-20200127145959-492f173dc3a2\code_pages.go:97:6: undefined: xlib.SortBytes        
go\pkg\mod\github.com\softlandia\cpd@v0.0.0-20200127145959-492f173dc3a2\utf16be.go:20:18: undefined: xlib.Max
go\pkg\mod\github.com\softlandia\cpd@v0.0.0-20200127145959-492f173dc3a2\utf16le.go:25:18: undefined: xlib.Max
PS Go\src\parse_ping_from_console_windows> go get github.com/softlandia/xlib
go: finding github.com/softlandia/xlib latest
PS Go\src\parse_ping_from_console_windows> go get -u github.com/softlandia/cpd
go: finding github.com/softlandia/cpd latest
go: finding github.com/softlandia/xlib latest
# github.com/softlandia/cpd
go\pkg\mod\github.com\softlandia\cpd@v0.0.0-20200127145959-492f173dc3a2\code_pages.go:97:6: undefined: xlib.SortBytes        
go\pkg\mod\github.com\softlandia\cpd@v0.0.0-20200127145959-492f173dc3a2\utf16be.go:20:18: undefined: xlib.Max
\go\pkg\mod\github.com\softlandia\cpd@v0.0.0-20200127145959-492f173dc3a2\utf16le.go:25:18: undefined: xlib.Max

**Comment by Rid-lin** [comment]
> Если что, конвертацию из CP866 в UTF-8 можно сделать одной строкой
> s, _, err = transform.String(charmap.CodePage866.NewDecoder(), s)

А вот за эту подсказку огромное спасибо.

**Comment by softlandia** [comment]
Ошибку проверяй, мне попадались ситуации когда операция проходила с ошибкой.

**Comment by softlandia** [comment]
Я чуть позже ещё обновлю, многопоточность заработает.

**Comment by Rid-lin** [comment]
Я про то что ошибка после обновления не ушла.

**Comment by softlandia** [comment]
Мне кажется нужно удалить полностью каталог /softlandia/ со всеми подкаталогами, а потом сделать go get github.com/softlandia/cpd
в той версии которая сейчас на github зависимостей внешних нет.

**Comment by Rid-lin** [comment]
Точно, помогло.
